default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: nopass
  port: 5432

development:
  <<: *default
  database: FamigliaSalerno_development

test:
  <<: *default
  database: FamigliaSalerno_test

production:
  <<: *default
  database: FamigliaSalerno_production
  username: FamigliaSalerno
  password: <%= ENV['FAMIGLIASALERNO_DATABASE_PASSWORD'] %>